const pianoState = {
  tone: null,
  note: [
    "C1",
    "Db1",
    "D1",
    "Eb1",
    "E1",
    "F1",
    "Gb1",
    "G1",
    "Ab1",
    "A1",
    "Bb1",
    "B1",

    "C2",
    "Db2",
    "D2",
    "Eb2",
    "E2",
    "F2",
    "Gb2",
    "G2",
    "Ab2",
    "A2",
    "Bb2",
    "B2",

    "C3",
    "Db3",
    "D3",
    "Eb3",
    "E3",
    "F3",
    "Gb3",
    "G3",
    "Ab3",
    "A3",
    "Bb3",
    "B3",

    "C4",
    "Db4",
    "D4",
    "Eb4",
    "E4",
    "F4",
    "Gb4",
    "G4",
    "Ab4",
    "A4",
    "Bb4",
    "B4",

    "C5",
    "Db5",
    "D5",
    "Eb5",
    "E5",
    "F5",
    "Gb5",
    "G5",
    "Ab5",
    "A5",
    "Bb5",
    "B5",

    "C6",
    "Db6",
    "D6",
    "Eb6",
    "E6",
    "F6",
    "Gb6",
    "G6",
    "Ab6",
    "A6",
    "Bb6",
    "B6",

    // "C7",
  ],
  chord: {
    C: {
      C: "C4,E4,G4",
      Cm: "C4,Eb4,G4",
      Cmaj7: "C4,E4,G4,B4",
      C7: "C4,E4,G4,Bb4",
      Cm7: "C4,Eb4,G4,Bb4",
      C7b9: "C4,E4,G4,Bb4,Db5",
      Csus4: "C4,F4,G4",
      CBass2: "C3,G3",
    },
    Db: {
      Db: "Db4,F4,Ab4",
      Dbm: "Db4,E4,Ab4",
      Dbmaj7: "Db4,F4,Ab4,C5",
      Db7: "Db4,F4,Ab4,B4",
      Dbm7: "Db4,E4,Ab4,B4",
      DbBass2: "Db3,Ab3",
    },
    D: {
      D: "D4,Gb4,A4",
      Dm: "D4,F4,A4",
      Dmaj7: "D4,Gb4,A4,Db5",
      D7: "D4,Gb4,A4,C5",
      Dm7: "D4,F4,A4,C5",
      DBass2: "D3,A3",
    },
    Eb: {
      Eb: "Eb4,G4,Bb4",
      Ebm: "Eb4,Gb4,Bb4",
      Ebmaj7: "Eb4,G4,Bb4,D5",
      Eb7: "Eb4,G4,Bb4,Db5",
      Ebm7: "Eb4,Gb4,Bb4,Db5",
      Eb6: "Eb4,G4,Bb4,C5",
      Eb7b9: "Eb4,G4,Bb4,Db5,E5",
      EbBass2: "Eb3,Bb3",
    },
    E: {
      E: "E4,Ab4,B4",
      Em: "E4,G4,B4",
      Emaj7: "E4,Ab4,B4,Eb5",
      E7: "E4,Ab4,B4,D5",
      Em7: "E4,G4,B4,D5",
      EBass2: "E3,B3",
    },
    F: {
      F: "F4,A4,C5",
      Fm: "F4,Ab4,C5",
      Fmaj7: "F4,A4,C5,E5",
      F7: "F4,A4,C5,Eb5",
      Fm7: "F4,Ab4,C5,Eb5",
      FBass2: "F3,C4",
    },
    Gb: {
      Gb: "Gb4,Bb4,Db5",
      Gbm: "Gb4,A4,Db5",
      Gbmaj7: "Gb4,Bb4,Db5,F5",
      Gb7: "Gb4,Bb4,Db5,E5",
      Gbm7: "Gb4,A4,Db5,E5",
      GbBass2: "Gb3,Db4",
    },
    G: {
      G: "G3,B3,D4",
      Gm: "G3,Bb3,D4",
      Gmaj7: "G3,B3,D4,Gb4",
      G7: "G3,B3,D4,F4",
      Gm7: "G3,Bb3,D4,F4",
      Gm7b5: "G3,Bb3,Db4,F4",
      GBass2: "G2,D3",
    },
    Ab: {
      Ab: "Ab3,C4,Eb4",
      Abm: "Ab3,B3,Eb4",
      Abmaj7: "Ab3,C4,Eb4,G4",
      Ab7: "Ab3,C4,Eb4,Gb4",
      Abm7: "Ab3,B3,Eb4,Gb4",
      Abm9: "Ab3,B3,Eb4,Gb4,Bb4",
      AbBass2: "Ab2,Eb3",
    },
    A: {
      A: "A3,Db4,E4",
      Am: "A3,C4,E4",
      Amaj7: "A3,Db4,E4,Ab4",
      A7: "A3,Db4,E4,G4",
      Am7: "A3,C4,E4,G4",
      ABass2: "A2,E3",
    },
    Bb: {
      Bb: "Bb3,D4,F4",
      Bbm: "Bb3,Db4,F4",
      Bbmaj7: "Bb3,D4,F4,A4",
      Bb7: "Bb3,D4,F4,Ab4",
      Bbm7: "Bb3,Db4,F4,Ab4",
      BbBass2: "Bb2,F3",
    },
    B: {
      B: "B3,Eb4,Gb4",
      Bm: "B3,D4,Gb4",
      Bmaj7: "B3,Eb4,Gb4,Bb4",
      B7: "B3,Eb4,Gb4,A4",
      BmOverD: "D4,Gb4,B4",
      Bm7: "B3,D4,Gb4,A4",
      BBass2: "B2,Gb3",
      BmOverDBass2: "D3,B3",
    },
  },
  keymap: {
    value: "jp",
    jp: {
      1: ["C", "C"],
      "!": ["C", "Cmaj7"],
      q: ["C", "Cm"],
      Q: ["C", "Cm7"],
      a: ["C", "C7"],
      z: ["C", "CBass2"],
      2: ["Db", "Db"],
      "@": ["Db", "Dbmaj7"],
      w: ["Db", "Dbm"],
      W: ["Db", "Dbm7"],
      s: ["Db", "Db7"],
      x: ["Db", "DbBass2"],
      3: ["D", "D"],
      "#": ["D", "Dmaj7"],
      e: ["D", "Dm"],
      E: ["D", "Dm7"],
      d: ["D", "D7"],
      c: ["D", "DBass2"],
      4: ["Eb", "Eb"],
      $: ["Eb", "Ebmaj7"],
      r: ["Eb", "Ebm"],
      R: ["Eb", "Ebm7"],
      f: ["Eb", "Eb7"],
      v: ["Eb", "EbBass2"],
      5: ["E", "E"],
      "%": ["E", "Emaj7"],
      t: ["E", "Em"],
      T: ["E", "Em7"],
      g: ["E", "E7"],
      b: ["E", "EBass2"],
      6: ["F", "F"],
      "^": ["F", "Fmaj7"],
      y: ["F", "Fm"],
      Y: ["F", "Fm7"],
      h: ["F", "F7"],
      n: ["F", "FBass2"],
      7: ["Gb", "Gb"],
      "&": ["Gb", "Gbmaj7"],
      u: ["Gb", "Gbm"],
      U: ["Gb", "Gbm7"],
      j: ["Gb", "Gb7"],
      m: ["Gb", "GbBass2"],
      8: ["G", "G"],
      "*": ["G", "Gmaj7"],
      i: ["G", "Gm"],
      I: ["G", "Gm7"],
      k: ["G", "G7"],
      ",": ["G", "GBass2"],
      9: ["Ab", "Ab"],
      "(": ["Ab", "Abmaj7"],
      o: ["Ab", "Abm"],
      O: ["Ab", "Abm7"],
      l: ["Ab", "Ab7"],
      ".": ["Ab", "AbBass2"],
      0: ["A", "A"],
      ")": ["A", "Amaj7"],
      p: ["A", "Am"],
      P: ["A", "Am7"],
      ";": ["A", "A7"],
      "/": ["A", "ABass2"],
      "-": ["Bb", "Bb"],
      "@": ["Bb", "Bbm"],
      _: ["Bb", "Bbmaj7"],
      "{": ["Bb", "Bbm7"],
      "'": ["Bb", "Bb7"],
      ArrowLeft: ["Bb", "BbBass2"],
      "^": ["B", "B"],
      "[": ["B", "Bm"],
      "]": ["B", "Bmaj7"],
      "}": ["B", "Bm7"],
      "\\": ["B", "B7"],
      "`": ["B", "BBass2"],
    },
    us: {
      1: ["C", "C"],
      "!": ["C", "Cmaj7"],
      q: ["C", "Cm"],
      Q: ["C", "Cm7"],
      a: ["C", "C7"],
      z: ["C", "CBass2"],
      2: ["Db", "Db"],
      "@": ["Db", "Dbmaj7"],
      w: ["Db", "Dbm"],
      W: ["Db", "Dbm7"],
      s: ["Db", "Db7"],
      x: ["Db", "DbBass2"],
      3: ["D", "D"],
      "#": ["D", "Dmaj7"],
      e: ["D", "Dm"],
      E: ["D", "Dm7"],
      d: ["D", "D7"],
      c: ["D", "DBass2"],
      4: ["Eb", "Eb"],
      $: ["Eb", "Ebmaj7"],
      r: ["Eb", "Ebm"],
      R: ["Eb", "Ebm7"],
      f: ["Eb", "Eb7"],
      v: ["Eb", "EbBass2"],
      5: ["E", "E"],
      "%": ["E", "Emaj7"],
      t: ["E", "Em"],
      T: ["E", "Em7"],
      g: ["E", "E7"],
      b: ["E", "EBass2"],
      6: ["F", "F"],
      "^": ["F", "Fmaj7"],
      y: ["F", "Fm"],
      Y: ["F", "Fm7"],
      h: ["F", "F7"],
      n: ["F", "FBass2"],
      7: ["Gb", "Gb"],
      "&": ["Gb", "Gbmaj7"],
      u: ["Gb", "Gbm"],
      U: ["Gb", "Gbm7"],
      j: ["Gb", "Gb7"],
      m: ["Gb", "GbBass2"],
      8: ["G", "G"],
      "*": ["G", "Gmaj7"],
      i: ["G", "Gm"],
      I: ["G", "Gm7"],
      k: ["G", "G7"],
      ",": ["G", "GBass2"],
      9: ["Ab", "Ab"],
      "(": ["Ab", "Abmaj7"],
      o: ["Ab", "Abm"],
      O: ["Ab", "Abm7"],
      l: ["Ab", "Ab7"],
      ".": ["Ab", "AbBass2"],
      0: ["A", "A"],
      ")": ["A", "Amaj7"],
      p: ["A", "Am"],
      P: ["A", "Am7"],
      ";": ["A", "A7"],
      "/": ["A", "ABass2"],
      "-": ["Bb", "Bb"],
      _: ["Bb", "Bbmaj7"],
      "[": ["Bb", "Bbm"],
      "{": ["Bb", "Bbm7"],
      "'": ["Bb", "Bb7"],
      ArrowLeft: ["Bb", "BbBass2"],
      "=": ["B", "B"],
      "+": ["B", "Bmaj7"],
      "]": ["B", "Bm"],
      "}": ["B", "Bm7"],
      "\\": ["B", "B7"],
      "`": ["B", "BBass2"],
    },
  },
};
