const pennyStore = mobx.observable({
  account: [],
  asset: [],
  budget: [],
  claim: [],
  config: {
    payday: 28,
    investForecast: {
      balance: 8000000,
      period: 1,
      periodUnit: "year",
    },
  },
  debt: [],
  deposit: [],
  form: {
    account: { mode: null, i: null, name: "", owner: "", balance: 0 },
    asset: {
      mode: null,
      i: null,
      name: "",
      owner: "",
      buyPrice: 0,
      sellPrice: 0,
    },
    asset: {
      mode: null,
      i: null,
      name: "",
      owner: "",
      buyPrice: 0,
      sellPrice: 0,
    },
    budget: {
      mode: null,
      i: null,
      name: "",
      amount: 0,
    },
    debt: {
      mode: null,
      i: null,
      id: null,
      name: "",
      owner: "",
      installment: 0,
      dueDate: "-",
      installmentLeft: 0,
    },
    deposit: { name: "", annualInterestRate: 0, type: "" },
    stuff: {
      mode: null,
      i: null,
      name: "",
      shopId: "",
      amount: 0,
      price: 0,
      unit: "",
    },
    stuffPrice: {
      mode: null,
      i: null,
      stuffI: null,
      stuffId: "",
      shopId: "",
      amount: 0,
      price: 0,
    },
    shop: {
      mode: null,
      i: null,
      name: "",
      owner: "",
      location: "",
      link: "",
    },
  },
  info: { name: "" },
  show: { balance: false },
  shop: [],
  stuff: [],
  stuffPrice: [],
});
