const drumAudio = {
  view: () => (
    <div id="audio">
      <audio
        id="sound-b"
        src="../../../asset/sound/drum/bass-5a.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-s"
        src="../../../asset/sound/drum/snare-5a.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-hc"
        src="../../../asset/sound/drum/hihat-closed-b1.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-ho"
        src="../../../asset/sound/drum/hihat-open-b1.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-c"
        src="../../../asset/sound/drum/crash.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-rc"
        src="../../../asset/sound/drum/ride-crash.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-st"
        src="../../../asset/sound/drum/stick.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-ts"
        src="../../../asset/sound/drum/tomtom-small-5a.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-tm"
        src="../../../asset/sound/drum/tomtom-medium-5a.ogg"
        preload="auto"
      ></audio>
      <audio
        id="sound-tf"
        src="../../../asset/sound/drum/tomtom-floor-5a.ogg"
        preload="auto"
      ></audio>
    </div>
  ),
};
