const gameState = {
  map: {
    bigegi84house: [
      [
        "wall",
        "wall",
        "wall",
        "wall",
        "door",
        "wall",
        "wall",
        "wall",
        "wall",
        "wall",
      ],
      [
        "tileGrass",
        "tileGrass",
        "tileGrass",
        "tileGrass",
        "tileGrass",
        "tileGrass",
        "tileGrass",
        "tileGrass",
        "tileGrass",
        "tileGrass",
      ],
      [
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
      ],
      [
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
      ],
      [
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
      ],
      [
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
      ],
      [
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
      ],
      [
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
      ],
      [
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
        "road",
      ],
    ],
  },
  sprite: {
    door: { type: "link", src: "app/game/sprite/door.svg" },
    road: { type: "link", src: "app/game/sprite/road.svg" },
    void: { type: "link", src: "app/game/sprite/void.svg" },
    tileGrass: { type: "link", src: "app/game/sprite/tile_grass.svg" },
    wall: { type: "link", src: "app/game/sprite/wall_4.png" },
  },
  world: {
    A: () => {
      const res = [
        gameState.map.bigegi84house,
        gameState.map.bigegi84house,
        gameState.map.bigegi84house,
        gameState.map.bigegi84house,
        gameState.map.bigegi84house,
        gameState.map.bigegi84house,
        gameState.map.bigegi84house,
        gameState.map.bigegi84house,
        gameState.map.bigegi84house,
      ];
      const merge = [];
      res.forEach((e, y) => {
        e.forEach(([...eA], x) => {
          const [...get] = _.get(merge, `${x}`, []);
          _.set(merge, `${x}`, [...get, ...eA]);
        });
      });
      console.log(merge);
      return merge;
    },
  },
};
