const knowledge = {
  word: {
    2: "2",
    5: "5",
    6: "6",
    8: "8",
    1994: "1994",
    1995: "1995",
    2019: "2019",
    9400: "9400",
    nama: "nama",
    kamu: "kamu",
    bigegi84: "bigegi84",
    siapa: "siapa",
    istri: "istri",
    Ririn: "Ririn",
    Marini: "Marini",
    Rusman: "Rusman",
    anak: "anak",
    Gemilang: "Gemilang",
    Syailendra: "Syailendra",
    Wiguna: "Wiguna",
    suka: "suka",
    apa: "apa",
    main: "main",
    "game,": "game,",
    ngoding: "ngoding",
    dll: "dll",
    asli: "asli",
    Gilang: "Gilang",
    Pratama: "Pratama",
    Jokowi: "Jokowi",
    presiden: "presiden",
    Indonesia: "Indonesia",
    Mahalini: "Mahalini",
    penyanyi: "penyanyi",
    mahalini: "mahalini",
    lagu: "lagu",
    "mahalini?": "mahalini?",
    iya: "iya",
    "banget,": "banget,",
    lagunya: "lagunya",
    bagus: "bagus",
    "Mahalini?": "Mahalini?",
    "siapa?": "siapa?",
    lengkap: "lengkap",
    "apa?": "apa?",
    negara: "negara",
    nomor: "nomor",
    hp: "hp",
    yang: "yang",
    belakangnya: "belakangnya",
    "+6288975329400": "+6288975329400",
    username: "username",
    ig: "ig",
    lu: "lu",
    woy: "woy",
    oy: "oy",
    halo: "halo",
    hi: "hi",
    email: "email",
    "gilangpw84@gmail.com": "gilangpw84@gmail.com",
    SMA: "SMA",
    dimana: "dimana",
    Negeri: "Negeri",
    Bogor: "Bogor",
    Kota: "Kota",
    lahir: "lahir",
    lagi: "lagi",
    ngapain: "ngapain",
    belajar: "belajar",
    nih: "nih",
    biar: "biar",
    pinter: "pinter",
    udah: "udah",
    makan: "makan",
    belum: "belum",
    w: "w",
    kan: "kan",
    komputer: "komputer",
    makannya: "makannya",
    "listrik,": "listrik,",
    kalo: "kalo",
    ga: "ga",
    ada: "ada",
    listrik: "listrik",
    mati: "mati",
    haha: "haha",
    oh: "oh",
    gemi: "gemi",
    eskrim: "eskrim",
    "suka,": "suka,",
    tiap: "tiap",
    hari: "hari",
    beli: "beli",
    tanggal: "tanggal",
    Maret: "Maret",
    mami: "mami",
    April: "April",
    banget: "banget",
    "ngoding?": "ngoding?",
    keren: "keren",
    "emang,": "emang,",
    dari: "dari",
    lang: "lang",
    bini: "bini",
    "gemi?": "gemi?",
    kuliah: "kuliah",
    Universitas: "Universitas",
    Jenderal: "Jenderal",
    Soedirman: "Soedirman",
    "dulu?": "dulu?",
  },
  sentence: {
    nama: {
      kamu: { siapa: { "@": "bigegi84" }, "siapa?": { "@": "bigegi84" } },
      asli: { kamu: { apa: { "@": "Gilang Pratama Wiguna" } } },
      lengkap: { kamu: { "apa?": { "@": "Gilang Pratama Wiguna" } } },
      lu: { siapa: { "@": "bigegi84" } },
    },
    kamu: {
      siapa: { "@": "bigegi84" },
      suka: {
        apa: { "@": "main game, ngoding dll" },
        lagu: { "mahalini?": { "@": "iya suka banget, lagunya bagus bagus" } },
        mahalini: { "@": "iya" },
        Mahalini: { "@": "iya" },
        "Mahalini?": { "@": "iya" },
      },
    },
    halo: { "@": "halo" },
    istri: {
      kamu: { siapa: { "@": "Ririn Marini Rusman" } },
      lu: { siapa: { "@": "Ririn Marini Rusman" } },
    },
    siapa: {
      istri: { kamu: { "@": "Ririn Marini Rusman" } },
      anak: { kamu: { "@": "Gemilang Syailendra Wiguna" } },
      lu: { "@": "bigegi84" },
      Ririn: { "@": "bini w" },
      "gemi?": { "@": "anak w" },
      gemi: { "@": "anak w" },
    },
    Jokowi: { siapa: { "@": "presiden Indonesia" } },
    Mahalini: { siapa: { "@": "penyanyi" } },
    mahalini: { siapa: { "@": "penyanyi" } },
    negara: {
      kamu: { "apa?": { "@": "Indonesia" }, apa: { "@": "Indonesia" } },
    },
    nomor: {
      hp: { yang: { belakangnya: { 9400: { "@": "+6288975329400" } } } },
      yang: { belakangnya: { 9400: { "@": "+6288975329400" } } },
    },
    username: { ig: { lu: { apa: { "@": "bigegi84" } } } },
    ig: { lu: { apa: { "@": "bigegi84" } } },
    lu: {
      siapa: { "@": "bigegi84" },
      SMA: { dimana: { "@": "SMA Negeri 5 Kota Bogor" } },
      lahir: { dimana: { "@": "Kota Bogor" } },
      suka: {
        ngoding: { "@": "suka banget" },
        "ngoding?": { "@": "suka banget" },
      },
      kuliah: {
        dimana: {
          "@": "Universitas Jenderal Soedirman",
          "dulu?": { "@": "Universitas Jenderal Soedirman" },
        },
      },
    },
    woy: { "@": "oy" },
    hi: { "@": "hi" },
    email: {
      lu: { "@": "gilangpw84@gmail.com", apa: { "@": "gilangpw84@gmail.com" } },
    },
    SMA: { dimana: { "@": "SMA Negeri 5 Bogor" } },
    lahir: { dimana: { "@": "Bogor" } },
    lagi: { ngapain: { "@": "lagi belajar nih biar pinter" } },
    udah: {
      makan: {
        belum: {
          "@": "w kan komputer makannya listrik, kalo ga ada listrik mati w haha",
        },
      },
    },
    oh: { iya: { "@": "haha" } },
    gemi: {
      suka: {
        eskrim: { ga: { "@": "suka, tiap hari makan eskrim" } },
        beli: { eskrim: { ga: { "@": "suka, tiap hari suka beli eskrim" } } },
      },
      "siapa?": { "@": "anak w" },
      siapa: { "@": "anak w" },
    },
    tanggal: {
      lahir: {
        gemi: { "@": "2 Maret 2019" },
        mami: { "@": "6 Maret 1994" },
        lu: { "@": "8 April 1995" },
      },
    },
    keren: { "@": "emang, dari lahir haha" },
    lang: { "@": "oy" },
    Ririn: { "siapa?": { "@": "bini w" }, siapa: { "@": "bini w" } },
  },
};
