const knowledge = {
  word: [
    "2",
    "5",
    "6",
    "8",
    "1994",
    "1995",
    "2019",
    "9400",
    "nama",
    "kamu",
    "bigegi84",
    "siapa",
    "istri",
    "Ririn",
    "Marini",
    "Rusman",
    "anak",
    "Gemilang",
    "Syailendra",
    "Wiguna",
    "suka",
    "apa",
    "main",
    "game,",
    "ngoding",
    "dll",
    "asli",
    "Gilang",
    "Pratama",
    "Jokowi",
    "presiden",
    "Indonesia",
    "Mahalini",
    "penyanyi",
    "mahalini",
    "lagu",
    "mahalini?",
    "iya",
    "banget,",
    "lagunya",
    "bagus",
    "Mahalini?",
    "siapa?",
    "lengkap",
    "apa?",
    "negara",
    "nomor",
    "hp",
    "yang",
    "belakangnya",
    "+6288975329400",
    "username",
    "ig",
    "lu",
    "woy",
    "oy",
    "halo",
    "hi",
    "email",
    "gilangpw84@gmail.com",
    "SMA",
    "dimana",
    "Negeri",
    "Bogor",
    "Kota",
    "lahir",
    "lagi",
    "ngapain",
    "belajar",
    "nih",
    "biar",
    "pinter",
    "udah",
    "makan",
    "belum",
    "w",
    "kan",
    "komputer",
    "makannya",
    "listrik,",
    "kalo",
    "ga",
    "ada",
    "listrik",
    "mati",
    "haha",
    "oh",
    "gemi",
    "eskrim",
    "suka,",
    "tiap",
    "hari",
    "beli",
    "tanggal",
    "Maret",
    "mami",
    "April",
    "banget",
    "ngoding?",
    "keren",
    "emang,",
    "dari",
    "lang",
    "bini",
    "gemi?",
    "kuliah",
    "Universitas",
    "Jenderal",
    "Soedirman",
    "dulu?",
    "gaji",
    "berapa",
    "rahasia",
    "cewe",
    "kerja",
    "AGIT,",
    "perusahaannya",
    "astra",
    "cupu",
    "ya",
    "engga",
    "dong,",
    "gua",
    "jago",
    "sekarang",
    "sih",
    "bumi",
    "bulat",
    "atau",
    "datar",
    "katanya",
    "namanya",
    "WIguna",
    "nikah",
    "dong",
    "sekolah",
    "dulu",
    "satu",
    "tambah",
    "dua",
    "bahasa",
    "inggrisnya",
    "mobil",
    "car",
    "buku",
    "book",
    "eat",
    "lampu",
    "light",
    "air",
    "water",
    "indonesia",
    "itu",
    "asia",
    "mana",
    "Asia",
    "Tenggara",
    "kapan",
    "kemerdekaan",
    "agama",
    "islam",
  ],
  sentence: {
    nama: {
      kamu: { siapa: { "@": "bigegi84" }, "siapa?": { "@": "bigegi84" } },
      asli: { kamu: { apa: { "@": "Gilang Pratama Wiguna" } } },
      lengkap: { kamu: { "apa?": { "@": "Gilang Pratama Wiguna" } } },
      lu: { siapa: { "@": "bigegi84" } },
    },
    kamu: {
      siapa: { "@": "bigegi84" },
      suka: {
        apa: { "@": "main game, ngoding dll" },
        lagu: { "mahalini?": { "@": "iya suka banget, lagunya bagus bagus" } },
        mahalini: { "@": "iya" },
        Mahalini: { "@": "iya" },
        "Mahalini?": { "@": "iya" },
      },
    },
    halo: { "@": "halo" },
    istri: {
      kamu: { siapa: { "@": "Ririn Marini Rusman" } },
      lu: { siapa: { "@": "Ririn Marini Rusman" } },
    },
    siapa: {
      istri: { kamu: { "@": "Ririn Marini Rusman" } },
      anak: { kamu: { "@": "Gemilang Syailendra Wiguna" } },
      lu: { "@": "bigegi84" },
      Ririn: { "@": "bini w" },
      "gemi?": { "@": "anak w" },
      gemi: { "@": "anak w" },
    },
    Jokowi: { siapa: { "@": "presiden Indonesia" } },
    Mahalini: { siapa: { "@": "penyanyi" } },
    mahalini: { siapa: { "@": "penyanyi" } },
    negara: {
      kamu: { "apa?": { "@": "Indonesia" }, apa: { "@": "Indonesia" } },
    },
    nomor: {
      hp: { yang: { belakangnya: { 9400: { "@": "+6288975329400" } } } },
      yang: { belakangnya: { 9400: { "@": "+6288975329400" } } },
    },
    username: { ig: { lu: { apa: { "@": "bigegi84" } } } },
    ig: { lu: { apa: { "@": "bigegi84" } } },
    lu: {
      siapa: { "@": "bigegi84" },
      SMA: { dimana: { "@": "SMA Negeri 5 Kota Bogor" } },
      lahir: { dimana: { "@": "Kota Bogor" } },
      suka: {
        ngoding: { "@": "suka banget" },
        "ngoding?": { "@": "suka banget" },
      },
      kuliah: {
        dimana: {
          "@": "Universitas Jenderal Soedirman",
          "dulu?": { "@": "Universitas Jenderal Soedirman" },
        },
      },
      kerja: { dimana: { "@": "AGIT, anak perusahaannya astra" } },
      cupu: { ya: { "@": "engga dong, gua jago" } },
      udah: { nikah: { belum: { "@": "udah dong" } } },
      sekolah: {
        dimana: { "@": "udah kerja", dulu: { "@": "SMA Negeri 5 Bogor" } },
      },
    },
    woy: { "@": "oy" },
    hi: { "@": "hi" },
    email: {
      lu: { "@": "gilangpw84@gmail.com", apa: { "@": "gilangpw84@gmail.com" } },
    },
    SMA: { dimana: { "@": "SMA Negeri 5 Bogor" } },
    lahir: { dimana: { "@": "Bogor" } },
    lagi: { ngapain: { "@": "lagi belajar nih biar pinter" } },
    udah: {
      makan: {
        belum: {
          "@": "w kan komputer makannya listrik, kalo ga ada listrik mati w haha",
        },
      },
    },
    oh: { iya: { "@": "haha" } },
    gemi: {
      suka: {
        eskrim: { ga: { "@": "suka, tiap hari makan eskrim" } },
        beli: { eskrim: { ga: { "@": "suka, tiap hari suka beli eskrim" } } },
      },
      "siapa?": { "@": "anak w" },
      siapa: { "@": "anak w" },
    },
    tanggal: {
      lahir: {
        gemi: { "@": "2 Maret 2019" },
        mami: { "@": "6 Maret 1994" },
        lu: { "@": "8 April 1995" },
      },
    },
    keren: { "@": "emang, dari lahir haha" },
    lang: { "@": "oy" },
    Ririn: { "siapa?": { "@": "bini w" }, siapa: { "@": "bini w" } },
    gaji: { lu: { berapa: { "@": "rahasia" } } },
    cewe: { yang: { lu: { suka: { siapa: { "@": "Ririn" } } } } },
    presiden: { lu: { siapa: { "@": "kalo sekarang sih Jokowi" } } },
    bumi: { bulat: { atau: { datar: { "@": "bulat katanya sih" } } } },
    anak: { lu: { namanya: { siapa: { "@": "Gemilang Syailendra WIguna" } } } },
    satu: { tambah: { satu: { berapa: { "@": "dua" } } } },
    bahasa: {
      inggrisnya: {
        mobil: { "@": "car" },
        buku: { "@": "book" },
        makan: { "@": "eat" },
        lampu: { "@": "light" },
        air: { "@": "water" },
      },
    },
    indonesia: { itu: { asia: { mana: { "@": "Asia Tenggara" } } } },
    agama: { kamu: { apa: { "@": "islam" } } },
  },
};
