const knowledge = {
  word: {
    9400: "9400",
    nama: "nama",
    kamu: "kamu",
    bigegi84: "bigegi84",
    siapa: "siapa",
    istri: "istri",
    Ririn: "Ririn",
    Marini: "Marini",
    Rusman: "Rusman",
    anak: "anak",
    Gemilang: "Gemilang",
    Syailendra: "Syailendra",
    Wiguna: "Wiguna",
    suka: "suka",
    apa: "apa",
    main: "main",
    "game,": "game,",
    ngoding: "ngoding",
    dll: "dll",
    asli: "asli",
    Gilang: "Gilang",
    Pratama: "Pratama",
    Jokowi: "Jokowi",
    presiden: "presiden",
    Indonesia: "Indonesia",
    Mahalini: "Mahalini",
    penyanyi: "penyanyi",
    mahalini: "mahalini",
    lagu: "lagu",
    "mahalini?": "mahalini?",
    iya: "iya",
    "banget,": "banget,",
    lagunya: "lagunya",
    bagus: "bagus",
    "Mahalini?": "Mahalini?",
    "siapa?": "siapa?",
    lengkap: "lengkap",
    "apa?": "apa?",
    negara: "negara",
    nomor: "nomor",
    hp: "hp",
    yang: "yang",
    belakangnya: "belakangnya",
    "+6288975329400": "+6288975329400",
    username: "username",
    ig: "ig",
    lu: "lu",
    woy: "woy",
    oy: "oy",
  },
  sentence: {
    nama: {
      kamu: { siapa: { "@": "bigegi84" }, "siapa?": { "@": "bigegi84" } },
      asli: { kamu: { apa: { "@": "Gilang Pratama Wiguna" } } },
      lengkap: { kamu: { "apa?": { "@": "Gilang Pratama Wiguna" } } },
    },
    kamu: {
      siapa: { "@": "bigegi84" },
      suka: {
        apa: { "@": "main game, ngoding dll" },
        lagu: { "mahalini?": { "@": "iya suka banget, lagunya bagus bagus" } },
        mahalini: { "@": "iya" },
        Mahalini: { "@": "iya" },
        "Mahalini?": { "@": "iya" },
      },
    },
    halo: { "@": "halo" },
    istri: {
      kamu: { siapa: { "@": "Ririn Marini Rusman" } },
      lu: { siapa: { "@": "Ririn Marini Rusman" } },
    },
    siapa: {
      istri: { kamu: { "@": "Ririn Marini Rusman" } },
      anak: { kamu: { "@": "Gemilang Syailendra Wiguna" } },
    },
    Jokowi: { siapa: { "@": "presiden Indonesia" } },
    Mahalini: { siapa: { "@": "penyanyi" } },
    mahalini: { siapa: { "@": "penyanyi" } },
    negara: {
      kamu: { "apa?": { "@": "Indonesia" }, apa: { "@": "Indonesia" } },
    },
    nomor: {
      hp: { yang: { belakangnya: { 9400: { "@": "+6288975329400" } } } },
      yang: { belakangnya: { 9400: { "@": "+6288975329400" } } },
    },
    username: { ig: { lu: { apa: { "@": "bigegi84" } } } },
    ig: { lu: { apa: { "@": "bigegi84" } } },
    lu: { siapa: { "@": "bigegi84" } },
    woy: { "@": "oy" },
  },
};
